name: Continuous integration testing

on:
  push:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - working-directory: ./app
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: akkor-api/package-lock.json
      - run: npm install
      - run: npm test
      